#!/usr/bin/python
import os

#For CGI handling
import cgi, cgitb

#For header and footer printing
import local_header_footer as lhf

#Create instance of FieldStorage
form = cgi.FieldStorage()

#Get data from fields
first_name = form.getvalue('first_name')
last_name = form.getvalue('last_name')

lhf.print_header("first_last get/post handler")

if first_name != None and last_name != None:
  print "<h2>Hello, %s %s</h2>"%(first_name, last_name)

lhf.print_footer()
